name: project_102
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_hotreload: ^1.4.0
  dart_code_metrics: ^5.7.3

dev_dependencies:
  dart_code_metrics: ^5.7.3
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
